const privacyPolicyEn = `1. Objective and Scope

This policy defines the regulatory, technical, and operational framework for the secure handling, processing, and storage of clinical data within the PneumOrpheus Computer-Aided Diagnosis (CAD) system. Developed primarily for the automated histological classification and staging of lung cancer, PneumOrpheus operates as a decoupled multi-tier architecture deployed on the Microsoft Azure cloud platform and is designed for seamless interoperability with hospital Picture Archiving and Communication Systems (PACS), specifically the Sectra IDS7 environment. This policy applies to all instances of the system, governing all interactions by clinical users, system administrators, and third-party processing modules.  

2. Legal Basis and Compliance Framework

PneumOrpheus processes medical imaging and patient demographics, which constitute "special category data" under Article 9 of the General Data Protection Regulation (GDPR). Data processing within the system is strictly governed by the following legal and ethical frameworks:

GDPR Articles 6 and 9:
Processing is permitted only when backed by explicit, freely given, specific, informed, and documented patient consent, or under strict public health and medical diagnosis exemptions (GDPR Article 9(2)(h)).

The Norwegian "Normen":
Technical implementations adhere to the Code of Conduct for Information Security and Data Protection in the Norwegian Health and Care Services (Normen). This ensures that cloud-based processing aligns with national cryptographic and risk management thresholds.

Data Protection Impact Assessments (DPIA):
Continuous compliance is maintained through regular DPIAs to evaluate the necessity and risk mitigation of machine learning inferences, scribing, and reporting functions.

3. Data Taxonomy and Minimization Protocols

In compliance with the GDPR principle of data minimization, PneumOrpheus restricts data ingestion to the "minimum necessary" components required to complete the diagnostic classification and staging tasks. The system handles three distinct categories of data:

Volumetric Imaging Data:
Raw multi-frame Digital Imaging and Communications in Medicine (DICOM) files uploaded via the frontend interface. These are automatically converted via a MONAI-based preprocessing pipeline into the Neuroimaging Informatics Technology Initiative (NIfTI) format to ensure isotropic voxel spacing and remove non-essential metadata headers.  

Patient Metadata:
Restricted to non-identifying clinical parameters relevant to lung cancer subtyping. Direct identifiers are completely scrubbed or pseudonymized at the hospital client side prior to cloud transmission.  

Diagnostic Outputs and Artifacts:
Computational outputs generated by the model(s), including ternary histological probability distributions, 3D bounding box coordinates for nodal stations, and post-hoc Explainable AI (XAI) assets such as Grad-CAM++ spatial saliency heatmaps.  

4. Architectural Security and Data Flow Protections

The multi-tier architecture implements a strict separation of concerns to safeguard data integrity and confidentiality during high-throughput deep learning inference :  

Data in Transit:
All communications between the presentation tier and the application tier are encrypted using Transport Layer Security (TLS 1.3) protocols.

Data at Rest:
Large binary objects, including the 3D NIfTI structural volumes and the generated Grad-CAM++ activation maps, are stored externally in secured Azure Blob Storage in the cloud. These assets are encrypted using Advanced Encryption Standard with 256-bit keys (AES-256). The relational database holds only the relative URL paths and serialized diagnostic metadata schemas, preventing the exposure of raw imaging files through the relational layer.  

Serverless Isolation:
Model inference is executed within containerized Docker environments managed by Azure Container Apps. These environments utilize "scale-to-zero" orchestration, ensuring that instances holding active patient data tokens are completely terminated and wiped from volatile memory when active processing jobs are concluded.  

5. Access Control and Departmental Governance

To protect against the unauthorized circulation or exploit of sensitive medical data, strict identity and access governance measures are enforced:

Authentication and MFA:
Identity management is brokered through Supabase's authentication tier, enforcing mandatory Multi-Factor Authentication (MFA) via unique user IDs and tokens for all accessing clinicians.  

Row-Level Security (RLS):
The underlying PostgreSQL instance implements strict RLS policies. RLS dynamically filters database queries based on the clinician's authentication, guaranteeing that a radiologist from a specific hospital trust can only view or interact with studies originating from their authorized domain.  

Role-Based Access Control (RBAC):
Privileges are segmented into explicit roles. Only authorized reading radiologists retain the cryptographic rights to modify segmented regions of interest or override the automated diagnostic reports.  

6. Immutable Audit Logging and Chain of Custody

To establish accountability and support regulatory compliance audits, PneumOrpheus maintains an independent, immutable audit trail logging every interaction within the application ecosystem:

Log Coverage:
The system records a detailed telemetry entry for every user event, including user authentication, image uploads, data conversions, model inference calls, report modifications, visual heatmap views, and data deletion requests.  

Log Structure:
Each log entry captures a cryptographically paired record containing a precise UTC timestamp, the unique user ID, the anonymized patient/analysis ID, the specific action performed, and the system component origin.  

Log Preservation:
Audit logs are decoupled from the operational application tier and stored in a read-only logging bucket, protecting the chain of custody against internal tampering or administrative overreach.  

7. Patient Rights, Retention, and the Right to Erasure

The system respects all personal data sovereignty requirements mandated by modern data protection regulations:

Right to Withdrawal and Erasure: 
In alignment with GDPR Article 17, patients maintain the right to withdraw data-processing consent at any time. PneumOrpheus urges all users to respect these rights in the handling of data used within the system, and if analysis or patient data is requested for deletion via the clinical portal, the platform executes a cascading delete: the raw and preprocessed volumes are purged from the secure cloud storage, and corresponding rows are deleted from the database instance.

Retraining Prohibitions:
Clinical scans ingested for routine diagnostic decision support are never automatically fed back into training loops or used for model optimization without distinct, standalone explicit consent. This separation blocks any implicit leakage of patient features through deep learning weights.`;

export default privacyPolicyEn;
